### ISSUE TITLE
FYI: strange-workaround-for-tftp-timeout-in-u-boot-bootloader

### ISSUE THREAD

**Issue by martin-zs** [lupyuen/nuttx-star64#2]
https://github.com/lupyuen/nuttx-star64#strange-workaround-for-tftp-timeout-in-u-boot-bootloader

Years ago I used to work in a mixed environment (Windows/Solaris/HP-US/Linux servers) and I noticed that most windows machines send an insane amount of packets in triplicate. UNIX would send everything once. This would make me wonder if the JH7110 SoC (or the licensed IP used) was only tested using windows machines.

My guess would be that if you setup a windows machine to be the tftp server, it would work - just because of the triple packets (mostly for UDP) .

**Comment by lupyuen** [comment]
Thank you so much for the tip! Too bad I don't have a Windows machine to test this. Our problem sounds similar to this:

- ["Downloading with U-Boot's tftp randomly times out"](https://serverfault.com/questions/669340/downloading-with-u-boots-tftp-randomly-times-out)

I'm writing an article about the workaround, I'll add your suggestion to the article. Thanks again! :-)

-   ["Strange Workaround for TFTP Timeout in U-Boot Bootloader (Star64 JH7110 SBC)"](https://lupyuen.github.io/articles/tftp2)
